### ISSUE TITLE
Dependency Conflict Between torch and nvidia-cuda-nvrtc-cu12 in conda env create

### ISSUE THREAD

**Issue by ouerwt** [wrh14/deep_unlearning#1]
I'm encountering dependency conflicts when trying to create a Conda environment using the `environment.yml` file. The issue arises between `torch` and `nvidia-cuda-nvrtc-cu12` versions.  

Here are the details:  
1. **Command:**  
   ```bash
   conda env create -f environment.yml
   ```
2. **Error Message:**  
   ```
   The conflict is caused by:
       The user requested nvidia-cuda-nvrtc-cu12==12.4.99
       torch 2.4.0 depends on nvidia-cuda-nvrtc-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64"
   To fix this you could try to:
   1. loosen the range of package versions you've specified
   2. remove package versions to allow pip to attempt to solve the dependency conflict
   ```
3. **Environment Configuration:**  
   The `environment.yml` specifies:
   - `torch==2.4.0`
   - `nvidia-cuda-nvrtc-cu12==12.4.99`  

   The versions seem incompatible as `torch 2.4.0` depends on `nvidia-cuda-nvrtc-cu12==12.1.105`.  

4. **Steps Taken:**  
   - Tried downgrading and upgrading `torch` versions (e.g., 2.3.0, 2.4.1, 2.5.0).  
   - Modified the environment file to loosen or fix version constraints.  
   - Encountered the same conflict each time due to the mismatched `nvidia-cuda-nvrtc-cu12` dependency.  

Could you provide guidance on how to resolve this dependency issue, or are there plans to align these package dependencies in future releases?  

Thank you!

**Comment by wrh14** [comment]
Thank you for raising this issue @ouerwt . The `environment.yml` has been updated. Please check and feel free to let me know if there is any other question!

**Comment by ouerwt** [comment]
@wrh14 Thank you! The new version works, and I was able to set up the environment successfully. 😊
